### ISSUE TITLE
Failed to read files

### ISSUE THREAD

**Issue by cnuts** [dmazz55/Pdfvert#2]
I am attempting to use the example in the readme but it fails.
var inputFile = "C:\\temp\\test.docx"; 
var outputFile = "C:\\temp\\test.pdf"; 

Exception:

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'cli_uretypes, Version=1.0.9.0, Culture=neutral, PublicKeyToken=ce2cb7e279207b9e' or one of its dependencies. The system cannot find the file specified.
  Source=Pdfvert
  StackTrace:
   at Pdfvert.Core.PdfvertService.ConvertFileToPdf(String inputFile, String outputFile)
   at MyProject.Program.Main(String[] args) in C:\Users\werdup\source\repos\MyProject\DocusignParser\Program.cs:line 26

I downloaded the SDK, adding the refs it complains about and then get the following:

System.ComponentModel.Win32Exception
  HResult=0x80004005
  Message=The system cannot find the file specified
  Source=System
  StackTrace:
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Pdfvert.Core.Utilities.OpenOfficeUtility.StartOpenOffice()
   at Pdfvert.Core.PdfvertService.ConvertFileToPdf(String inputFile, String outputFile)
   at DocusignParser.Program.Main(String[] args) in C:\Users\werdup\source\repos\DocusignCollections\DocusignParser\Program.cs:line 26

I can firm beyond a doubt the source file exsits.  I've also tried WPD files - same error.

**Comment by dmazz55** [comment]
What version of the SDK did you install?

**Comment by dmazz55** [comment]
You don't need to download the SDK. That's mentioned in the readme. The DLLs are included in the NuGet package. But you do need to install OpenOffice 4.1.2.

**Comment by dmazz55** [comment]
Can you verify you have OpenOffice 4.1.2 installed? and If not, what version do you have installed?

**Comment by cnuts** [comment]
My apologies, I thought any dependencies were included in the nuget package.  Installed, it converts now.  A two page WPD file to a PDF is 300+ pages though with garbage text.

**Comment by dmazz55** [comment]
Unfortunately that’s going to be an issue for OpenOffice I’m glad you got it working, but I’m sorry the result wasn’t what you we’re hoping for.
